// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package postgresdriver

import ()

type Node struct {
	NodeID               int32  `json:"nodeID"`
	NodeAddress          string `json:"nodeAddress"`
	NodeAverageLatency   int32  `json:"nodeAverageLatency"`
	NodeUptimePercentage int32  `json:"nodeUptimePercentage"`
	NodeErrorPercentage  int32  `json:"nodeErrorPercentage"`
	IsAltruistNode       bool   `json:"isAltruistNode"`
	ChainID              int32  `json:"chainID"`
}

type NodeChain struct {
	NodeChainID  int32  `json:"nodeChainID"`
	NodeAddress  string `json:"nodeAddress"`
	CurrentStake int64  `json:"currentStake"`
	ChainID      int32  `json:"chainID"`
}
